name:                halg-factor
version:             0.6.0.0
github:              "konn/halg-factor"
license:             BSD3
author:              "Hiromi ISHII"
maintainer:          "konn.jinro _at_ gmail.com"
copyright:           "2018 (c) Hiromi ISHII"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Polynomial factorisation algorithms, part of halg computational algebra suite.
category:            Math

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the project Web Site <https://konn.github.io/computational-algebra>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:  -Wall
  dependencies:
  - MonadRandom
  - algebra
  - algebraic-prelude
  - arithmoi
  - containers
  - control-monad-loop
  - dlist
  - halg-core
  - halg-polynomials
  - integer-logarithms
  - lens
  - monad-loops
  - mtl
  - primes
  - sized
  - type-natural
  - vector
  default-extensions:
  - NoImplicitPrelude

executables: {}

tests: {}
