language_extensions:
- CPP
- DataKinds
- DerivingStrategies
- ExplicitNamespaces
- ExtendedDefaultRules
- FlexibleContexts
- FlexibleInstances
- GADTs
- KindSignatures
- MultiParamTypeClasses
- OverloadedLabels
- PolyKinds
- ScopedTypeVariables
- TypeFamilies
- TypeInType
- UndecidableInstances

steps:
- imports:
    align: group
- language_pragmas:
    style: compact_line
    remove_redundant: true
- trailing_whitespace: {}

columns: 80
