# This file has been generated -- see https://github.com/hvr/multi-ghc-travis
language: c
sudo: false

cache:
  directories:
    - $HOME/.cabsnap
    - $HOME/.stack

matrix:
  include:
    - env: STACK_YAML=stack-800.yaml
      compiler: ": #GHC 8.0.2"
      addons:
        apt:
          packages:
            - libgmp3-dev
            - libgsl0-dev
            - liblapack-dev
    - env: STACK_YAML=stack-802.yaml
      compiler: ": #GHC 8.2.2"
      addons:
        apt:
          packages:
            - libgmp3-dev
            - libgsl0-dev
            - liblapack-dev

before_install:
 # install Stack
 - mkdir -p ~/.local/bin
 - export PATH=$HOME/.local/bin:$PATH
 - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
 - unset CC
 - export PATH=$HOME/.local/bin:/opt/ghc/$GHCVER/bin:$PATH
 - stack setup

install:
 - stack --version
 - stack build --jobs=3 --only-dependencies
 - stack build --jobs=3 --test --only-dependencies

# Here starts the actual work to be performed for the package under test;
# any command which exits with a non-zero exit code causes the build to fail.
script:
 -  travis_wait 30 stack --jobs=3 --no-terminal --skip-ghc-check test

# Check that the resulting source distribution can be built & installed.
# If there are no other `.tar.gz` files in `dist`, this can be even simpler:
# `cabal install --force-reinstalls dist/*-*.tar.gz`
# EOF
