resolver: lts-11.4
skip-ghc-check: true
packages:
- 'computational-algebra'
- 'algebraic-prelude'
- 'halg-core'
- 'halg-core-test'
- 'halg-polynomials'
- 'halg-galois-fields'
- 'halg-heaps'
- 'halg-matrices'
- 'halg-algorithms'
- 'halg-polyn-parser'
- 'halg-factor'
- 'halg-algebraic'
- 'halg-bridge-singular'

flags:
  computational-algebra:
    examples: true
    profile:  false

build:
  library-profiling: true
  executable-profiling: false
  haddock: true

extra-deps:
- control-monad-loop-0.1
- algebra-4.3
- ghc-typelits-presburger-0.2.0.0
- unamb-0.2.5
- hspec-smallcheck-0.5.0
- type-natural-0.8.0.1
- git: https://github.com/konn/sized.git
  commit: 48a4778329c8a7779e7f914126f8aa08f94551a2
- git: https://github.com/konn/equational-reasoning-in-haskell.git
  commit: 69bcb461fd8d497a99ca22daa150797f22d03ad4
