resolver: nightly-2016-08-02
packages:
- '.'
- location:
    git: https://github.com/konn/sized.git
    commit: 0b17f9fd9c80acb0387100bcf3afd57eed7c519f
  extra-dep: true

- location:
    git: https://github.com/konn/algebra.git
    commit: 5dd837dd0540ff64ea748d68927508ba62555734
  extra-dep: true

- location:
    git: https://github.com/konn/type-natural.git
    commit: eec3a2c139245db68c32a22ab2bba4844f694b57
  extra-dep: true

- location:
    git: https://github.com/konn/equational-reasoning-in-haskell.git
    commit: af0457b760efa333da086507381a4af1ea5354e3
  extra-dep: true

flags:
  computational-algebra:
    examples: true

extra-deps:
- control-monad-loop-0.1
- ghc-typelits-natnormalise-0.4.6
- repa-3.4.1.1
- repa-algorithms-3.4.1.1
- trifecta-1.6
- type-natural-0.6.0.0
- equational-reasoning-0.4.1.1
- ghc-typelits-presburger-0.1.1.0
- monomorphic-0.0.3.3
- singletons-2.2
- presburger-1.3.1
- unamb-0.2.5
- lazysmallcheck-0.6
# - sized-vector-1.4.3.1
