resolver: lts-6.9
extra-deps:
- algebra-4.2
- equational-reasoning-0.4.0.0
- monomorphic-0.0.3.3
- sized-vector-1.4.3.1
- sparse-0.9.2
- type-natural-0.4.1.0
- unamb-0.2.5
- ghc-typelits-presburger-0.1.0.0
- singletons-2.1
- th-desugar-1.6
- presburger-1.3.1
- adjunctions-4.2.2
- bifunctors-4.2.1
- distributive-0.4.4
- lens-4.9.1
- profunctors-4.4.1
- reflection-1.5.2.1
- repa-3.4.0.1
- repa-algorithms-3.4.0.1
- semigroupoids-4.3
- vector-0.10.12.3

# flags:
#   semigroups:
#     bytestring-builder: false
