resolver: nightly-2016-08-02
packages:
- '.'
- 'algebraic-prelude'

- location:
    git: https://github.com/konn/type-natural.git
    commit: 843498255722471249a36fb821eabb4409e75bc2
  extra-dep: true
- location:
    git: https://github.com/konn/sized.git
    commit: 37bc1b1a68ead7de8ae3dc18f9e037ff49e491c8
  extra-dep: true

flags:
  computational-algebra:
    examples: false

# build:
#   haddock: true

extra-deps:
- control-monad-loop-0.1
- ghc-typelits-natnormalise-0.4.6
- repa-3.4.1.1
- repa-algorithms-3.4.1.1
- trifecta-1.6
- type-natural-0.7.1.0
- equational-reasoning-0.4.1.1
- ghc-typelits-presburger-0.1.1.0
- monomorphic-0.0.3.3
- singletons-2.2
- presburger-1.3.1
- unamb-0.2.5
- lazysmallcheck-0.6
- algebra-4.3
# - sized-0.2.0.0
