name:                halg-algorithms
version:             0.6.0.0
github:              "konn/halg-groebner"
license:             BSD3
author:              "Hiromi ISHII"
maintainer:          "konn.jinro _at_ gmail.com"
copyright:           "2018 (c) Hiromi ISHII"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Algorithms related to Gröbner basis, part of halg computational algebra suite.
category:            Math

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the project Web Site <https://konn.github.io/computational-algebra>

default-extensions:
- CPP
- DataKinds
- FlexibleContexts
- FlexibleInstances
- GADTs
- MultiParamTypeClasses
- OverloadedLabels
- PolyKinds
- TypeFamilies
- TypeInType
- UndecidableInstances  

dependencies:
- base >= 4.7 && < 5
- halg-core
- halg-polynomials
- algebra
- MonadRandom
- sized

library:
  source-dirs: src
  other-modules:
  - Algebra.Algorithms.FGLM
  ghc-options:  -Wall
  dependencies:
  - ghc-typelits-knownnat
  - sized
  - algebraic-prelude
  - containers
  - convertible
  - monad-loops
  - equational-reasoning
  - halg-matrices
  - heaps
  - hmatrix
  - lens
  - matrix
  - monad-loops
  - mtl
  - reflection
  - vector
  default-extensions:
  - NoImplicitPrelude

tests:
  spec:
    main:                Spec.hs
    source-dirs:         test
    other-modules:
    - ZeroDimSpec
    - HomogeneousSpec
    - Utils
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HUnit
    - ghc-typelits-knownnat
    - halg-core-test
    - halg-polynomials
    - halg-algorithms
    - halg-bridge-singular
    - QuickCheck
    - convertible
    - containers
    - equational-reasoning
    - hspec
    - lens
    - matrix
    - quickcheck-instances
    - reflection
    - smallcheck
    - type-natural
    - vector
    - hspec-discover

benchmarks:
  homog-bench:
    source-dirs:  bench
    main:         homog-bench.hs
    dependencies:
    - halg-algorithms
    - gauge
    - parallel
