hackage:
  prefix:  http://hackage.haskell.org/package/

asin:
  prefix:  http://www.amazon.co.jp/dp/

github:
  prefix:  https://github.com/

doc:
  prefix:  https://konn.github.io/computational-algebra/docs/computational-algebra-0.4.0.0/
