name:                halg-containers
version:             0.1.0.0
github:              "konn/halg-containers"
license:             BSD3
author:              "Hiromi ISHII"
maintainer:          "konn.jinro _at_ gmail.com"
copyright:           "2018 (c) Hiromi ISHII"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/konn/halg-containers#readme>

dependencies:
- algebraic-prelude
- base >= 4.7 && < 5
- containers
- deepseq
- hashable
- intern

library:
  source-dirs: src
  ghc-options:
  - -O2
  other-modules:
  - Data.Map.Interned.Internal

# executables:
#   halg-containers-exe:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     - -Wall
#     dependencies:
#     - halg-containers

# tests:
#   halg-containers-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - halg-containers
